name: NodeJS with Webpack

on:
  push:
    branches: [step2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: 14 

    - run: npm ci 
    - run: npm run build-step2 
    
    - uses: peaceiris/actions-main@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
